config/routes.rb
Panoramic::Application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "users#index"
  resources :users
  resources :sessions
end

app/models/kml.rb
class Kml < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    before_create {generate_token(:auth_token)}

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

private
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end

      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      redirect_to root_url, notice: "Invalid Email or Password"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url notice: "Logged out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      cookies.permanent[:auth_token] = @user.auth_token
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "New"
    end
  end






  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Panoramic</title>
    <!--Only loads google earth api once a user has logged in -->
    <% if current_user %>
      <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <% end %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", logout_path%>
  <% else %>
    <%= link_to "Sign Up", signup_path%>
        <div>
      <p>Log In</p>
        <%= form_tag sessions_path do %>
          <div class="field">
            <%= label_tag :email %><br />
            <%= text_field_tag :email, params[:email] %>
          </div>
          <div class="field">
            <%= label_tag :password %><br />
            <%= password_field_tag :password %>
          </div>
          <div class="field">
            <%= check_box_tag :remember_me, 1, params[:remember_me] %>
            <%= label_tag :remember_me %>
          </div>
          <div class="actions"><%= submit_tag "Log In" %></div>
        <% end %>
      </div>
  <% end %>
</header>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

<!--Only displays google earth api once a user has logged in -->
<% if current_user %>
  <div id="map3d" style="height: 70%; width: 50%;"></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>WELCOME BRYAN</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username%>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>